### ISSUE TITLE
Add a handler for an empty path

### ISSUE THREAD

**Issue by cjwirth** [usebutton/DeepLinkKit#29]
This may or may not be a controversial request, but it would be nice to have a handler for an empty path.

In my app, because of reasons, we have a url like `http://ourapp.com/?certainId={id}` come in. I thought I could handle it with `self.router.registerBlock(block, forRoute: "")` but it didn't catch it...

**Comment by chrismaddern** [comment]
Hey @cjwirth - currently, you can achieve this using the regex support on the route.. `.*`

```swift
self.router.registerBlock(block, forRoute: ".*")
```

If you'd like to extend support for empty routes, it'd be great to see a P/R

**Comment by chrismaddern** [comment]
Closing issue as it is possible :smile:
