### ISSUE TITLE
DeepLinking to Apps which are not Installed yet?

### ISSUE THREAD

**Issue by confile** [usebutton/DeepLinkKit#37]
Is it possible to DeepLink to Apps which are not Installed yet?

**Comment by chrismaddern** [comment]
@confile Not yet. ;)

**Comment by confile** [comment]
@chrismaddern Is it possible in general?

**Comment by chrismaddern** [comment]
Not without a lot of work.

We built AttendedInstall at Button for exactly that :)
https://s3-us-west-2.amazonaws.com/button-cdn/content/button-uber-resy-hinted.mov

**Comment by confile** [comment]
@chrismaddern Where can I get AttendedInstall?

**Comment by chrismaddern** [comment]
It's currently not available separate from the Button DeepLink Commerce SDK.

Coming soon ;)

**Comment by confile** [comment]
@chrismaddern Could you invite me for private beta?

Is there a timeline when it will be available?

**Comment by garfbargle** [comment]
@chrismaddern The "AttendedInstall" is awesome.
