### ISSUE TITLE
Rename iOS DeepLink SDK -> ??

### ISSUE THREAD

**Issue by chrismaddern** [usebutton/DeepLinkKit#44]
Would love any comments on this... currently thinking something like:

- RouteKit
- DeepLinkKit
- DeepLinkRouter

The term SDK isn't really a good description of the 'weight' of this library so we wanted to drop it.

**Comment by pcperini** [comment]
+1 RouteKit

**Comment by chrismaddern** [comment]
InterAppKit came up

**Comment by wessmith** [comment]
I like RouteKit the best but, it has the disadvantages of not including "deep link", not being representative of the library actually being a deep link creation tool, and would disassociate the library name from the name-spacing (or require re-name-spacing). 

InterAppKit sounds too app specific. While this library is very useful for app-to-app deep linking, it also handles deep links from other sources.

**Comment by buttonpairing** [comment]
DeepLinkKit it is!
