### ISSUE TITLE
Installation without CocoaPods

### ISSUE THREAD

**Issue by iliaskarim** [usebutton/DeepLinkKit#46]
Please provide installation instructions for use without CocoaPods

**Comment by danqing** [comment]
Will be great if this can support Carthage!

**Comment by iliaskarim** [comment]
Carthage support would be awesome

**Comment by hankbao** [comment]
:+1:

**Comment by Snoops** [comment]
Any update on how to install without Cocoapods ? Thanks

**Comment by iliaskarim** [comment]
@Snoops we just included the source files form DeepLinkKit in our project

**Comment by Snoops** [comment]
Ah yes thank you !

**Comment by wessmith** [comment]
Currently, if you don't use CocoaPods, you can include all of the source files from the [DeepLinkKit directory](https://github.com/usebutton/DeepLinkKit/tree/master/DeepLinkKit) in your project.
