### ISSUE TITLE
url from attribute

### ISSUE THREAD

**Issue by wuminglan** [usebutton/DeepLinkKit#54]
hi,  there is a such url 
mailto:foo@example.com?cc=bar@example.com&subject=Greetings%20from%20Cupertino!&body=Wish%20you%20were%20here!

how to get the attributes

**Comment by wessmith** [comment]
You can get the url parameters from a `DPLDeepLink` instance via the `queryParameters` [property](https://github.com/usebutton/DeepLinkKit/blob/master/DeepLinkKit/DeepLink/DPLDeepLink.h#L26):
`deepLink.queryParameters[@"subject"]`

You can also use direct subscripting on the deepLink:
`deepLink[@"subject"]`
