### ISSUE TITLE
DPLDeepLinkRouteHandler is gone

### ISSUE THREAD

**Issue by adly-holler** [usebutton/DeepLinkKit#64]
The documentation mentions this protocol but it seems to be gone. =(

**Comment by adly-holler** [comment]
@chrismaddern The documentation now says `DPLRouteHandler protocol` but `DPLRouteHandler` isn't a protocol.

**Comment by chrismaddern** [comment]
D'oh! nice catch!

**Comment by platedbay** [comment]
Oh whoops! Want me to grab that?

**Comment by chrismaddern** [comment]
@platedbay @adly-holler R: https://github.com/usebutton/DeepLinkKit/pull/67

**Comment by chrismaddern** [comment]
@adly-holler andd..... actually fixed.

**Comment by adly-holler** [comment]
@chrismaddern Cool, thanks. Great framework BTW, excited to use this in a new project.
