### ISSUE TITLE
Swift demo or examples?

### ISSUE THREAD

**Issue by basememara** [usebutton/DeepLinkKit#65]
Great framework, thanks! Is there a Swift demo or examples anywhere? It would be immensely appreciated and a step in the right direction for better Swift support.

**Comment by platedbay** [comment]
I'm working through implementing this in Swift now and would love to take a stab at making a Swift demo. Would you guys prefer a new .xcodeproj, like `DeepLinkKit-Swift`?

**Comment by chrismaddern** [comment]
@platedbay Nice!

Currently they're all in one xcodeproj & am happy to have the Swift one in there too if it doesn't break anything. If that's not the best option then happy to have a new Xcodeproj.
